#ifndef __PDFIUM_H__
#define __PDFIUM_H__

// auto generated by mkmf
#include "extconf.h"

#ifdef DEBUG
#define debug_printf(M, ...) fprintf(stderr, "DEBUG %s:%d: " M "\n", __FILE__, __LINE__, ##__VA_ARGS__)
#else
#define debug_printf(M, ...)
#endif


#endif // __PDFIUM_H__
