Document: pdfium
Title: Debian pdfium Manual
Author: <insert document author here>
Abstract: This manual describes what pdfium is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pdfium/pdfium.sgml.gz

Format: postscript
Files: /usr/share/doc/pdfium/pdfium.ps.gz

Format: text
Files: /usr/share/doc/pdfium/pdfium.text.gz

Format: HTML
Index: /usr/share/doc/pdfium/html/index.html
Files: /usr/share/doc/pdfium/html/*.html
